sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t erickrdze/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true erickrdze/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  environment: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-033454698408"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"